### ISSUE TITLE
where io_tools?

### ISSUE THREAD

**Issue by HPW-dev** [bebuch/tar#6]
need io_tools headers

**Comment by bebuch** [comment]
@HPW-dev These are both old projects that are no longer under active development. Be warned!

You can find the io_tools project here:

https://github.com/bebuch/io_tools

I can't guaranty that the current trunk of io_tools works with the current trunk of my tar project.

**Comment by HPW-dev** [comment]
> I can't guaranty that the current trunk of io_tools works with the current trunk of my tar project.

ok
